### ISSUE TITLE
Training keeps getting killed

### ISSUE THREAD

**Issue by andyElking** [ExplainableML/uot-fm#4]
Hi!

I've been trying to get your code to work, but whenever I run training I get a crash. No error message, it just says `Killed`. The same thing happens when I run `compute_fid_reference_stats.py` (it does some stuff, a bunch of progress bars go through fine, then it just dies). So my questions are:

- For example, when I do a training run with `celeba64/female/fm.py`, I get through two progress meters, then there's a few seconds of nothing and then the console just says `Killed` (if run from PyCharm it just crashes). What do those two progress bars represent? Their length doesn't change if I change the `training.num_steps` or any of the other training parameters, so I assume they're to do with loading the data or something. But I can't seem to find their origin.
- Could it be that my computer specs are just too weak? I have a mobile RTX 4080 (12GB VRAM), i9-13900HX, 32GB RAM. If that is not enough I can run it on an HPC, but I was hoping I could just do a shorter training run directly on my laptop, just to get familiar with the code.
- Do you have any suggestions how I could start diagnosing this issue? I'm not getting error messages, just a `Killed`. And the logs also just say the following:

```
INFO - main.py - 2024-08-29 15:27:06,234 - Using CUDA devices 0
INFO - xla_bridge.py - 2024-08-29 15:27:07,685 - Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
INFO - xla_bridge.py - 2024-08-29 15:27:07,685 - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO - datasets.py - 2024-08-29 15:27:10,641 - Loading source and target data.
```

Thank you!

**Comment by lucaeyring** [comment]
Hi, thank you for your interest in our work!

The way the current codebase is setup, is that it loads the full dataset into memory (RAM) and, as CelebA is larger than 32GB, the run will be killed when the RAM is exhausted. Additionally, the CelebA training runs also need a good amount of GPU memory depending on the batch-size used. The 64x64 training runs in the default setting were conducted with 8x 40GB A100s.

The MNIST-example should be able to run on your machine if you are interested in testing UOT-FM locally. Otherwise, I would recommend switching to an HPC.

**Comment by andyElking** [comment]
Thanks! Yes, I switched to an HPC and indeed it works now. Thank you for the claraification!
